=== UZHCMS/ph1_TriDAS/pixel/PixelAnalysisTools/dtd/PixelAnalysis.dtd
<!-- DTD for the pixel analysis scripts xml initialization files -->
<!-- Authors: E. Luiggi, B. Heyburn , L. Uplegger -->


<!ELEMENT PixelAnalysis ( Calibration, WhichWBC, Logger, Session, ConfigurationFiles, RootOutputFile, NumberOfEvents, Hardware, SCurveCuts* , GainCuts* , PixelAliveCuts* ) >

<!ELEMENT Calibration EMPTY >
<!ATTLIST Calibration  Type (SCurve|PixelAlive|Gain) "SCurve" >

<!ELEMENT WhichWBC EMPTY>
<!ATTLIST WhichWBC ChooseWBC CDATA #REQUIRED>

<!ELEMENT Logger EMPTY >
<!ATTLIST Logger  Type (cout|file) "cout" >

<!ELEMENT Session EMPTY >
<!ATTLIST Session  Interactive (yes|no) "yes" >

<!ELEMENT ConfigurationFiles ( DefaultDirectory | (CalibFileName, TranslationFileName, DetConfigFileName)) >

<!ELEMENT RootOutputFile EMPTY>
<!ATTLIST RootOutputFile 
  Directory CDATA #REQUIRED 
  FileName  CDATA #REQUIRED>

<!ELEMENT DefaultDirectory EMPTY >
<!ATTLIST DefaultDirectory Directory CDATA #REQUIRED >

<!ELEMENT CalibFileName EMPTY >
<!ATTLIST CalibFileName FileName   CDATA #REQUIRED >

<!ELEMENT TranslationFileName EMPTY >
<!ATTLIST TranslationFileName FileName   CDATA #REQUIRED >

<!ELEMENT DetConfigFileName EMPTY >
<!ATTLIST DetConfigFileName FileName   CDATA #REQUIRED >

<!ELEMENT NumberOfEvents EMPTY > 
<!ATTLIST NumberOfEvents Events CDATA #REQUIRED >

<!-- Add fed elements here -->
<!ELEMENT Hardware ( Feds ) >

<!ELEMENT Feds ( Fed+ ) >
<!ATTLIST Feds Analyze CDATA #REQUIRED >

<!ELEMENT Fed (DataFileName, Channels, Rocs) >
<!ATTLIST Fed Id CDATA #REQUIRED >

<!ELEMENT DataFileName EMPTY >
<!ATTLIST DataFileName FileName   CDATA #REQUIRED >

<!ELEMENT Channels EMPTY>
<!ATTLIST Channels 
  From CDATA #REQUIRED 
  To   CDATA #REQUIRED
  Exclude CDATA #IMPLIED>
 
<!ELEMENT Rocs EMPTY >
<!ATTLIST Rocs Exclude CDATA #REQUIRED >

<!ELEMENT Fit ((Ntrials, Startcurve, Endcurve)*,(FitFunctions,LinearFit,TanhFit)*) >
<!ELEMENT Flag ((SaveHistograms, NoiseSigma, RocNoiseMean, RocThresholdMean, RocChisquareMean, RocProbabilityMean, OutputTrimFile, SaveGoodFits)*,(BadPixels)*,(SaveHistograms, RocSlopeMean, RocInterceptMean, LinearChisquareMean, LinearProbabilityMean, TanhLinearityMean)*)>

<!ELEMENT SCurveCuts (Fit, Flag) >
<!--SCurve Fit Cuts-->
<!ELEMENT Ntrials EMPTY >
<!ATTLIST Ntrials Trials CDATA #REQUIRED >
<!ELEMENT Startcurve EMPTY >
<!ATTLIST Startcurve Value CDATA #REQUIRED >
<!ELEMENT Endcurve EMPTY >
<!ATTLIST Endcurve Value CDATA #REQUIRED >

<!--SCurve Flag Cuts-->
<!ELEMENT NoiseSigma EMPTY >
<!ATTLIST NoiseSigma Min CDATA #REQUIRED >
<!ELEMENT RocNoiseMean EMPTY>
<!ATTLIST RocNoiseMean Max CDATA #REQUIRED>
<!ELEMENT RocThresholdMean EMPTY>
<!ATTLIST RocThresholdMean Max CDATA #REQUIRED>
<!ELEMENT RocChisquareMean EMPTY>
<!ATTLIST RocChisquareMean Max CDATA #REQUIRED>
<!ELEMENT RocProbabilityMean EMPTY>
<!ATTLIST RocProbabilityMean Min CDATA #REQUIRED>
<!ELEMENT OutputTrimFile EMPTY>
<!ATTLIST OutputTrimFile Write (Yes|No) "No">
<!ELEMENT SaveGoodFits EMPTY>
<!ATTLIST SaveGoodFits DoIt (Yes|No) "No">

<!ELEMENT GainCuts (Fit, Flag) >
<!--Gain Fit Cuts-->
<!ELEMENT FitFunctions EMPTY >
<!ATTLIST FitFunctions Functions (linear|tanh|linear-tanh|tanh-linear) "linear" >
<!ELEMENT LinearFit EMPTY >
<!ATTLIST LinearFit 
	From CDATA #REQUIRED
	To   CDATA #REQUIRED>
<!ELEMENT TanhFit EMPTY >
<!ATTLIST TanhFit 
	From CDATA #REQUIRED
	To   CDATA #REQUIRED>
<!--Gain Flag Cuts-->
<!ELEMENT RocSlopeMean EMPTY>
<!ATTLIST RocSlopeMean Max CDATA #REQUIRED>
<!ELEMENT RocInterceptMean EMPTY>
<!ATTLIST RocInterceptMean Max CDATA #REQUIRED>
<!ELEMENT LinearChisquareMean EMPTY>
<!ATTLIST LinearChisquareMean Max CDATA #REQUIRED>
<!ELEMENT LinearProbabilityMean EMPTY>
<!ATTLIST LinearProbabilityMean Min CDATA #REQUIRED>
<!ELEMENT TanhLinearityMean EMPTY>
<!ATTLIST TanhLinearityMean Max CDATA #REQUIRED>

<!--Gain SCurve Flag Cuts-->
<!ELEMENT SaveHistograms EMPTY>
<!ATTLIST SaveHistograms Max CDATA #REQUIRED>


<!ELEMENT PixelAliveCuts (Flag) >
<!--PixelAlive Flag Cuts-->
<!ELEMENT BadPixels EMPTY >
<!ATTLIST BadPixels Max CDATA #REQUIRED >

=== UZHCMS/ph1_TriDAS/pixel/PixelAnalysisTools/test/configuration/SCurveAnalysis_BaseExample.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<!DOCTYPE PixelAnalysis SYSTEM "../../dtd/PixelAnalysis.dtd">
<PixelAnalysis>
  <!--There are 3 types of calibrations available: SCurve,PixelAlive,Gain. -->
  <Calibration Type="SCurve" />
  <!-- Set to WBC to analyze or 999 for all WBCs-->
  <WhichWBC ChooseWBC="999"/>
  <!--Can only be cout or file. -->
  <Logger      Type="cout" />
  <Session     Interactive="yes" />
  <!-- The 3 configuration files necessary to run the analysis using also environment variables-->
	<!-- calib.dat,translation.dat,detconfig.dat --> 
	<!-- altenatively you can provide a DefaultDirectory where the 3 files are stored
	     but they MUST have the 3 standard names calib.dat,translation.dat,detectconfig.dat
			 and then run the test providing as a second argument just the run number.--> 
  <ConfigurationFiles>
    <!--
		<DefaultDirectory    Directory="$POS_OUTPUT_DIRS" />
 	  -->
    <CalibFileName       FileName="/FPixData/FPIX/HC+Z1/Runs_warm_886_888/PixelConfigDataExamples_BpO_All/calib/15/calib.dat" />
    <TranslationFileName FileName="/FPixData/FPIX/HC+Z1/Runs_warm_886_888/PixelConfigDataExamples_BpO_All/nametranslation/0/translation.dat" />
    <DetConfigFileName   FileName="/FPixData/FPIX/HC+Z1/Runs_warm_886_888/PixelConfigDataExamples_BpO_All/detconfig/0/detectconfig.dat" />
  </ConfigurationFiles>
  <RootOutputFile     Directory="Default" FileName="Default" />
  <!--RootOutputFile     Directory="$BUILD_HOME/pixel/PixelAnalysisTools/test/RootOutputFiles" FileName="Default" /-->
  <!--Number of events that the user wants to process. -1 means that all data will be processed -->
  <NumberOfEvents Events="-1"/>
  <Hardware>
    <!-- Feds that user wants to analyze dash separated-->
    <Feds Analyze="33-34">
        <!-- Data file name assciated with the fed you want to analyze using also environment variables. 
				     If The DefaultDirectory tag is used providing as a second argument the run number 
						 then the keyword Default can be used-->
      <Fed Id="33">
        <!-- Data file name assciated with the fed you want to analyze using also environment variables. 
				     If The DefaultDirectory tag is used providing as a second argument the run number 
						 then the keyword Default can be used-->
        <!--
        <DataFileName        FileName="Default" /> 
				-->
        <DataFileName        FileName="/FPixData/FPIX/HC+Z1/Runs_warm_886_888/SCurve_33_888.dmp" />
        <!-- Fed channels that you want to analyze. 
				    Some channels between from and to can be excluded writing a list dash separated
						If From="1" and To="36" all channels active in the configuration will be analyzed-->
        <Channels From="13" To="36" Exclude=""/>
        <!-- Dash separated list of Rocs that you want to exclude from the analysis-->
        <Rocs     Exclude=""/>
      </Fed>
      <!-- Second fed that you want to analyze-->
      <Fed Id="34">
        <!--
        <DataFileName        FileName="Default" /> 
				-->
        <DataFileName      FileName="/FPixData/FPIX/HC+Z1/Runs_warm_886_888/SCurve_34_888.dmp" />
        <Channels From="1" To="24" Exclude=""/>
        <Rocs     Exclude=""/>
      </Fed>
    </Feds>
  </Hardware>  
  <SCurveCuts>
    <Fit>
      <!-- Number of times a fit is attempted before giving up-->
			<Ntrials            Trials="5"/>
      <!-- Point where to find the beginning of the SCurve here 10%-->
      <Startcurve         Value="0.1"/>
      <!-- Point where to find the end of the SCurve here 90%-->
      <Endcurve           Value="0.9"/>
    </Fit>
    <Flag>
      <!-- Maximum number of Noisy and Error histogram to be saved-->
      <SaveHistograms     Max="2000"/>
      <!-- This flags the Scurve as noisy based on the rms of the fit. The histogram is saved in the noisy directory-->
      <NoiseSigma         Min="4"/>
      <!-- Rocs with a mean sigma on the noise greater than the value are printed out and marked as bad-->
      <RocNoiseMean       Max="3"/>
      <!-- Rocs with a mean Threshold greater than the value are printed out and marked as bad-->
      <RocThresholdMean   Max="130"/>
      <!-- Rocs with a mean Chisquare greater than the value are printed ou56288: TrimDefaultShort56294: TrimVcThrShort.56300: TrimVtrimShort56303: TrimOnShort56305: TrimOffShortt and marked as bad-->
      <RocChisquareMean   Max="2"/>
      <!-- Rocs with a mean Confidence level greater than the value are printed out and marked as bad-->
      <RocProbabilityMean Min="0.9"/>
      <!-- Print trim output file for trimming analysis (Yes|No)-->
      <OutputTrimFile     Write="No"/>
      <!-- Example of good histograms (Yes|No)-->
      <SaveGoodFits       DoIt="No"/>
    </Flag>
   </SCurveCuts>
</PixelAnalysis>
